// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNoPyt_XXx-uebMIkdWZZHxC1cZFJlOzc',
    appId: '1:740236615990:web:6fc6228bc78faa868dd397',
    messagingSenderId: '740236615990',
    projectId: 'sigesit-143f5',
    authDomain: 'sigesit-143f5.firebaseapp.com',
    storageBucket: 'sigesit-143f5.appspot.com',
    measurementId: 'G-EEKE102J6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaAfIgbmnrSHHJNQ0MtIjR7vrDOPYAkmE',
    appId: '1:740236615990:android:5c7ee6e55ca7b3e48dd397',
    messagingSenderId: '740236615990',
    projectId: 'sigesit-143f5',
    storageBucket: 'sigesit-143f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB89EB7i_DuoHEYWJP_mnvQpLv4if-aMLA',
    appId: '1:740236615990:ios:c55b101328c0ac538dd397',
    messagingSenderId: '740236615990',
    projectId: 'sigesit-143f5',
    storageBucket: 'sigesit-143f5.appspot.com',
    androidClientId: '740236615990-3veaab4u84oqdkimbc0n644od0bdmauo.apps.googleusercontent.com',
    iosClientId: '740236615990-tcqfvkim87ifemv5e0iuh4h91qd9u7gk.apps.googleusercontent.com',
    iosBundleId: 'com.sim.cleanerdev',
  );
}
