// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBHf9G8Nnv_jcwX4OJxjgdYJwJ8JISwLQ',
    appId: '1:118145354533:android:bf99625ad65a8f2d86a8cc',
    messagingSenderId: '118145354533',
    projectId: 'dptbantuan',
    storageBucket: 'dptbantuan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlexPVT-oeMscWaqkh2KIIEzCYqEuhykU',
    appId: '1:118145354533:ios:9c545e32bd906d8886a8cc',
    messagingSenderId: '118145354533',
    projectId: 'dptbantuan',
    storageBucket: 'dptbantuan.appspot.com',
    iosClientId: '118145354533-jtiiodj1ig2oqpral1trlpqrnbvfueij.apps.googleusercontent.com',
    iosBundleId: 'com.tama.dpt',
  );
}
